/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.client.model.ApplePayPaymentRequest;
import com.hyperswitch.client.model.ApplePaySessionResponse;
import com.hyperswitch.client.model.SdkNextAction;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApplepaySessionTokenResponse
 */
@JsonPropertyOrder({
  ApplepaySessionTokenResponse.JSON_PROPERTY_SESSION_TOKEN_DATA,
  ApplepaySessionTokenResponse.JSON_PROPERTY_PAYMENT_REQUEST_DATA,
  ApplepaySessionTokenResponse.JSON_PROPERTY_CONNECTOR,
  ApplepaySessionTokenResponse.JSON_PROPERTY_DELAYED_SESSION_TOKEN,
  ApplepaySessionTokenResponse.JSON_PROPERTY_SDK_NEXT_ACTION,
  ApplepaySessionTokenResponse.JSON_PROPERTY_CONNECTOR_REFERENCE_ID,
  ApplepaySessionTokenResponse.JSON_PROPERTY_CONNECTOR_SDK_PUBLIC_KEY,
  ApplepaySessionTokenResponse.JSON_PROPERTY_CONNECTOR_MERCHANT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-28T20:00:07.865622+05:30[Asia/Kolkata]")
public class ApplepaySessionTokenResponse {
  public static final String JSON_PROPERTY_SESSION_TOKEN_DATA = "session_token_data";
  private ApplePaySessionResponse sessionTokenData;

  public static final String JSON_PROPERTY_PAYMENT_REQUEST_DATA = "payment_request_data";
  private JsonNullable<ApplePayPaymentRequest> paymentRequestData = JsonNullable.<ApplePayPaymentRequest>undefined();

  public static final String JSON_PROPERTY_CONNECTOR = "connector";
  private String connector;

  public static final String JSON_PROPERTY_DELAYED_SESSION_TOKEN = "delayed_session_token";
  private Boolean delayedSessionToken;

  public static final String JSON_PROPERTY_SDK_NEXT_ACTION = "sdk_next_action";
  private SdkNextAction sdkNextAction;

  public static final String JSON_PROPERTY_CONNECTOR_REFERENCE_ID = "connector_reference_id";
  private JsonNullable<String> connectorReferenceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CONNECTOR_SDK_PUBLIC_KEY = "connector_sdk_public_key";
  private JsonNullable<String> connectorSdkPublicKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CONNECTOR_MERCHANT_ID = "connector_merchant_id";
  private JsonNullable<String> connectorMerchantId = JsonNullable.<String>undefined();

  public ApplepaySessionTokenResponse() {
  }

  public ApplepaySessionTokenResponse sessionTokenData(ApplePaySessionResponse sessionTokenData) {
    
    this.sessionTokenData = sessionTokenData;
    return this;
  }

   /**
   * Get sessionTokenData
   * @return sessionTokenData
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SESSION_TOKEN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ApplePaySessionResponse getSessionTokenData() {
    return sessionTokenData;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_TOKEN_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionTokenData(ApplePaySessionResponse sessionTokenData) {
    this.sessionTokenData = sessionTokenData;
  }


  public ApplepaySessionTokenResponse paymentRequestData(ApplePayPaymentRequest paymentRequestData) {
    this.paymentRequestData = JsonNullable.<ApplePayPaymentRequest>of(paymentRequestData);
    
    return this;
  }

   /**
   * Get paymentRequestData
   * @return paymentRequestData
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public ApplePayPaymentRequest getPaymentRequestData() {
        return paymentRequestData.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUEST_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ApplePayPaymentRequest> getPaymentRequestData_JsonNullable() {
    return paymentRequestData;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUEST_DATA)
  public void setPaymentRequestData_JsonNullable(JsonNullable<ApplePayPaymentRequest> paymentRequestData) {
    this.paymentRequestData = paymentRequestData;
  }

  public void setPaymentRequestData(ApplePayPaymentRequest paymentRequestData) {
    this.paymentRequestData = JsonNullable.<ApplePayPaymentRequest>of(paymentRequestData);
  }


  public ApplepaySessionTokenResponse connector(String connector) {
    
    this.connector = connector;
    return this;
  }

   /**
   * The session token is w.r.t this connector
   * @return connector
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONNECTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConnector() {
    return connector;
  }


  @JsonProperty(JSON_PROPERTY_CONNECTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConnector(String connector) {
    this.connector = connector;
  }


  public ApplepaySessionTokenResponse delayedSessionToken(Boolean delayedSessionToken) {
    
    this.delayedSessionToken = delayedSessionToken;
    return this;
  }

   /**
   * Identifier for the delayed session response
   * @return delayedSessionToken
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELAYED_SESSION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDelayedSessionToken() {
    return delayedSessionToken;
  }


  @JsonProperty(JSON_PROPERTY_DELAYED_SESSION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelayedSessionToken(Boolean delayedSessionToken) {
    this.delayedSessionToken = delayedSessionToken;
  }


  public ApplepaySessionTokenResponse sdkNextAction(SdkNextAction sdkNextAction) {
    
    this.sdkNextAction = sdkNextAction;
    return this;
  }

   /**
   * Get sdkNextAction
   * @return sdkNextAction
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SDK_NEXT_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SdkNextAction getSdkNextAction() {
    return sdkNextAction;
  }


  @JsonProperty(JSON_PROPERTY_SDK_NEXT_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSdkNextAction(SdkNextAction sdkNextAction) {
    this.sdkNextAction = sdkNextAction;
  }


  public ApplepaySessionTokenResponse connectorReferenceId(String connectorReferenceId) {
    this.connectorReferenceId = JsonNullable.<String>of(connectorReferenceId);
    
    return this;
  }

   /**
   * The connector transaction id
   * @return connectorReferenceId
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getConnectorReferenceId() {
        return connectorReferenceId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONNECTOR_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getConnectorReferenceId_JsonNullable() {
    return connectorReferenceId;
  }
  
  @JsonProperty(JSON_PROPERTY_CONNECTOR_REFERENCE_ID)
  public void setConnectorReferenceId_JsonNullable(JsonNullable<String> connectorReferenceId) {
    this.connectorReferenceId = connectorReferenceId;
  }

  public void setConnectorReferenceId(String connectorReferenceId) {
    this.connectorReferenceId = JsonNullable.<String>of(connectorReferenceId);
  }


  public ApplepaySessionTokenResponse connectorSdkPublicKey(String connectorSdkPublicKey) {
    this.connectorSdkPublicKey = JsonNullable.<String>of(connectorSdkPublicKey);
    
    return this;
  }

   /**
   * The public key id is to invoke third party sdk
   * @return connectorSdkPublicKey
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getConnectorSdkPublicKey() {
        return connectorSdkPublicKey.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONNECTOR_SDK_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getConnectorSdkPublicKey_JsonNullable() {
    return connectorSdkPublicKey;
  }
  
  @JsonProperty(JSON_PROPERTY_CONNECTOR_SDK_PUBLIC_KEY)
  public void setConnectorSdkPublicKey_JsonNullable(JsonNullable<String> connectorSdkPublicKey) {
    this.connectorSdkPublicKey = connectorSdkPublicKey;
  }

  public void setConnectorSdkPublicKey(String connectorSdkPublicKey) {
    this.connectorSdkPublicKey = JsonNullable.<String>of(connectorSdkPublicKey);
  }


  public ApplepaySessionTokenResponse connectorMerchantId(String connectorMerchantId) {
    this.connectorMerchantId = JsonNullable.<String>of(connectorMerchantId);
    
    return this;
  }

   /**
   * The connector merchant id
   * @return connectorMerchantId
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getConnectorMerchantId() {
        return connectorMerchantId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONNECTOR_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getConnectorMerchantId_JsonNullable() {
    return connectorMerchantId;
  }
  
  @JsonProperty(JSON_PROPERTY_CONNECTOR_MERCHANT_ID)
  public void setConnectorMerchantId_JsonNullable(JsonNullable<String> connectorMerchantId) {
    this.connectorMerchantId = connectorMerchantId;
  }

  public void setConnectorMerchantId(String connectorMerchantId) {
    this.connectorMerchantId = JsonNullable.<String>of(connectorMerchantId);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplepaySessionTokenResponse applepaySessionTokenResponse = (ApplepaySessionTokenResponse) o;
    return Objects.equals(this.sessionTokenData, applepaySessionTokenResponse.sessionTokenData) &&
        equalsNullable(this.paymentRequestData, applepaySessionTokenResponse.paymentRequestData) &&
        Objects.equals(this.connector, applepaySessionTokenResponse.connector) &&
        Objects.equals(this.delayedSessionToken, applepaySessionTokenResponse.delayedSessionToken) &&
        Objects.equals(this.sdkNextAction, applepaySessionTokenResponse.sdkNextAction) &&
        equalsNullable(this.connectorReferenceId, applepaySessionTokenResponse.connectorReferenceId) &&
        equalsNullable(this.connectorSdkPublicKey, applepaySessionTokenResponse.connectorSdkPublicKey) &&
        equalsNullable(this.connectorMerchantId, applepaySessionTokenResponse.connectorMerchantId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionTokenData, hashCodeNullable(paymentRequestData), connector, delayedSessionToken, sdkNextAction, hashCodeNullable(connectorReferenceId), hashCodeNullable(connectorSdkPublicKey), hashCodeNullable(connectorMerchantId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplepaySessionTokenResponse {\n");
    sb.append("    sessionTokenData: ").append(toIndentedString(sessionTokenData)).append("\n");
    sb.append("    paymentRequestData: ").append(toIndentedString(paymentRequestData)).append("\n");
    sb.append("    connector: ").append(toIndentedString(connector)).append("\n");
    sb.append("    delayedSessionToken: ").append(toIndentedString(delayedSessionToken)).append("\n");
    sb.append("    sdkNextAction: ").append(toIndentedString(sdkNextAction)).append("\n");
    sb.append("    connectorReferenceId: ").append(toIndentedString(connectorReferenceId)).append("\n");
    sb.append("    connectorSdkPublicKey: ").append(toIndentedString(connectorSdkPublicKey)).append("\n");
    sb.append("    connectorMerchantId: ").append(toIndentedString(connectorMerchantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

