/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.client.model.FieldTypeOneOf;
import com.hyperswitch.client.model.FieldTypeOneOf1;
import com.hyperswitch.client.model.FieldTypeOneOf2;
import com.hyperswitch.client.model.FieldTypeOneOf3;
import com.hyperswitch.client.model.FieldTypeOneOfUserCountry;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Possible field type of required fields in payment_method_data
 */
@JsonPropertyOrder({
  FieldType.JSON_PROPERTY_USER_COUNTRY,
  FieldType.JSON_PROPERTY_USER_CURRENCY,
  FieldType.JSON_PROPERTY_USER_ADDRESS_COUNTRY,
  FieldType.JSON_PROPERTY_DROP_DOWN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-28T20:00:07.865622+05:30[Asia/Kolkata]")
public class FieldType {
  public static final String JSON_PROPERTY_USER_COUNTRY = "user_country";
  private FieldTypeOneOfUserCountry userCountry;

  public static final String JSON_PROPERTY_USER_CURRENCY = "user_currency";
  private FieldTypeOneOfUserCountry userCurrency;

  public static final String JSON_PROPERTY_USER_ADDRESS_COUNTRY = "user_address_country";
  private FieldTypeOneOfUserCountry userAddressCountry;

  public static final String JSON_PROPERTY_DROP_DOWN = "drop_down";
  private FieldTypeOneOfUserCountry dropDown;

  public FieldType() {
  }

  public FieldType userCountry(FieldTypeOneOfUserCountry userCountry) {
    
    this.userCountry = userCountry;
    return this;
  }

   /**
   * Get userCountry
   * @return userCountry
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FieldTypeOneOfUserCountry getUserCountry() {
    return userCountry;
  }


  @JsonProperty(JSON_PROPERTY_USER_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserCountry(FieldTypeOneOfUserCountry userCountry) {
    this.userCountry = userCountry;
  }


  public FieldType userCurrency(FieldTypeOneOfUserCountry userCurrency) {
    
    this.userCurrency = userCurrency;
    return this;
  }

   /**
   * Get userCurrency
   * @return userCurrency
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FieldTypeOneOfUserCountry getUserCurrency() {
    return userCurrency;
  }


  @JsonProperty(JSON_PROPERTY_USER_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserCurrency(FieldTypeOneOfUserCountry userCurrency) {
    this.userCurrency = userCurrency;
  }


  public FieldType userAddressCountry(FieldTypeOneOfUserCountry userAddressCountry) {
    
    this.userAddressCountry = userAddressCountry;
    return this;
  }

   /**
   * Get userAddressCountry
   * @return userAddressCountry
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FieldTypeOneOfUserCountry getUserAddressCountry() {
    return userAddressCountry;
  }


  @JsonProperty(JSON_PROPERTY_USER_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserAddressCountry(FieldTypeOneOfUserCountry userAddressCountry) {
    this.userAddressCountry = userAddressCountry;
  }


  public FieldType dropDown(FieldTypeOneOfUserCountry dropDown) {
    
    this.dropDown = dropDown;
    return this;
  }

   /**
   * Get dropDown
   * @return dropDown
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DROP_DOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FieldTypeOneOfUserCountry getDropDown() {
    return dropDown;
  }


  @JsonProperty(JSON_PROPERTY_DROP_DOWN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDropDown(FieldTypeOneOfUserCountry dropDown) {
    this.dropDown = dropDown;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldType fieldType = (FieldType) o;
    return Objects.equals(this.userCountry, fieldType.userCountry) &&
        Objects.equals(this.userCurrency, fieldType.userCurrency) &&
        Objects.equals(this.userAddressCountry, fieldType.userAddressCountry) &&
        Objects.equals(this.dropDown, fieldType.dropDown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userCountry, userCurrency, userAddressCountry, dropDown);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldType {\n");
    sb.append("    userCountry: ").append(toIndentedString(userCountry)).append("\n");
    sb.append("    userCurrency: ").append(toIndentedString(userCurrency)).append("\n");
    sb.append("    userAddressCountry: ").append(toIndentedString(userAddressCountry)).append("\n");
    sb.append("    dropDown: ").append(toIndentedString(dropDown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

