/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.client.model.GiftCardDataOneOf;
import com.hyperswitch.client.model.GiftCardDataOneOf1;
import com.hyperswitch.client.model.GiftCardDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GiftCardData
 */
@JsonPropertyOrder({
  GiftCardData.JSON_PROPERTY_GIVEX,
  GiftCardData.JSON_PROPERTY_PAY_SAFE_CARD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-28T20:00:07.865622+05:30[Asia/Kolkata]")
public class GiftCardData {
  public static final String JSON_PROPERTY_GIVEX = "givex";
  private GiftCardDetails givex;

  public static final String JSON_PROPERTY_PAY_SAFE_CARD = "pay_safe_card";
  private Object paySafeCard;

  public GiftCardData() {
  }

  public GiftCardData givex(GiftCardDetails givex) {
    
    this.givex = givex;
    return this;
  }

   /**
   * Get givex
   * @return givex
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GIVEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GiftCardDetails getGivex() {
    return givex;
  }


  @JsonProperty(JSON_PROPERTY_GIVEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGivex(GiftCardDetails givex) {
    this.givex = givex;
  }


  public GiftCardData paySafeCard(Object paySafeCard) {
    
    this.paySafeCard = paySafeCard;
    return this;
  }

   /**
   * Get paySafeCard
   * @return paySafeCard
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_SAFE_CARD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getPaySafeCard() {
    return paySafeCard;
  }


  @JsonProperty(JSON_PROPERTY_PAY_SAFE_CARD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaySafeCard(Object paySafeCard) {
    this.paySafeCard = paySafeCard;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCardData giftCardData = (GiftCardData) o;
    return Objects.equals(this.givex, giftCardData.givex) &&
        Objects.equals(this.paySafeCard, giftCardData.paySafeCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(givex, paySafeCard);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCardData {\n");
    sb.append("    givex: ").append(toIndentedString(givex)).append("\n");
    sb.append("    paySafeCard: ").append(toIndentedString(paySafeCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

